package {
	
	/**
	 * ...
	 * @author Alex
	 */
	public class Data {
		public static const NICKNAMES:Array/*String*/ = ['A. D.', 'The A-Train', 'The Admiral', 'Air Canada', 'Air Jordan', 'Agent Zero', 'AK-47', 'B.Easy', 'Babe Ruth', 'Baby Jordan', 'Baron', 'Maestro', 'Bear', 'Bells', 'The Big D', 'The Big E', 'The Big O', 'Big Baby', 'Big Country', 'Big House', 'Big Red', 'Birdman', 'Black Jesus', 'Black Mamba', 'Blaze', 'Boki', 'Booger', 'Cap', 'Catfish', 'Caveman', 'CB4', 'The Closer', 'Chief', 'Clyde', 'The Cooz', 'Cornbread', 'CP3', 'Crash', 'Creeper', 'Da Kid', 'D-Fish', 'D-Rose', 'D-Wade', 'D-Will', 'DJ', 'Deke', 'Dice', 'The Diesel', 'The Dobber', 'Dr. J', 'The Doctor', 'Doggie', 'Dollar Bill', 'Dugie', 'Durantula', 'El Sid', 'Flash', 'Flight', 'The Goat', 'The Glove', 'The Hawk', 'Helicopter', 'The Hibachi', 'His Airness', 'Hondo', 'Honey', 'The Iceman', 'Il Mago', 'Invincible', 'J-Kidd', 'The Jet', 'Joe D', 'Jumpin\' Joe', 'KG', 'King James', 'K.Love', 'Krypto-Nate', 'L.A.', 'Linsanity', 'The Logo', 'Luke', 'Mad Max', 'The Mailman', 'Manimal', 'The Matrix', 'Melo', 'Mighty Mite', 'MJ', 'The Mogul', 'Mookie', 'Mount', 'Mr. 81', 'Mr. Clutch', 'Moose', 'Muggsy', 'Murph', 'The Natural', 'Nique', 'Pac-Man', 'The Pearl', 'Penny', 'Piggy', 'Pistol Pete', 'Pitchin\' Paul', 'Poison', 'Prof', 'The Queen', 'Red', 'Rip', 'Satch', 'Shaq', 'Shaqovic', 'Silk', 'Sir Charles', 'Sir Sid', 'Skywalker', 'Spree', 'The Spider', 'Starbury', 'Stretch', 'Superman', 'Sweetwater', 'Tarzan', 'Tanketa', 'Tiny', 'T-Mac', 'The Truth', 'Uptown', 'Vinsanity', 'White Mamba', 'World', 'The Wizard', 'The Worm', 'X-Man', 'Z', 'Big Z', 'Zeke', 'Zo'];
		
		public static const PLANET_NAMES:Array/*String*/ = ['Moon', 'Phobos', 'Deimos', 'Dactyl', 'Linus', 'Io', 'Europa', 'Ganymede', 'Callisto', 'Amalthea', 'Himalia', 'Elara', 'Pasiphae', 'taurus', 'Sinope', 'Lysithea', 'Carme', 'Ananke', 'Leda', 'Thebe', 'Adrastea', 'Metis', 'Callirrhoe', 'Themisto', '1975', '2000', 'Megaclite', 'Taygete', 'Chaldene', 'Harpalyke', 'Kalyke', 'Iocaste', 'Erinome', 'Isonoe', 'Praxidike', 'Autonoe', 'Thyone', 'Hermippe', 'Aitne', 'Eurydome', 'Euanthe', 'Euporie', 'Orthosie', 'Sponde', 'Seasons', 'Kale', 'Pasithee', 'Hegemone', 'Mneme', 'Aoede', 'Thelxinoe', 'Arche', 'Kallichore', 'Helike', 'Carpo', 'Eukelade', 'Cyllene', 'Kore', 'Herse', 'Selene', 'Mimas', 'or Ares', 'Enceladus', 'Tethys', 'Dione', 'by Zeus', 'Rhea', 'Titan', 'Titans', 'Hyperion', 'Iapetus', 'Phoebe', 'Janus', 'Dollfus', 'Pascu', 'Dollfus', 'Pascu', 'Epimetheus', 'Cruikshank', 'Helene', 'Telesto', 'Calypso', 'Atlas', 'Prometheus', 'Pandora', 'Pan', 'Ymir', 'Paaliaq', 'Tarvos', 'Ijiraq', 'Suttungr', 'Kiviuq', 'Mundilfari', 'Albiorix', 'Skathi', 'Erriapus', 'Siarnaq', 'Thrymr', 'Narvi', 'Methone', 'Pallene', 'Polydeuces', 'Daphnis', 'Aegir', 'Bebhionn', 'Bergelmir', 'Bestla', 'Farbauti', 'Fenrir', 'Fornjot', 'Hati', 'Hyrrokkin', 'Kari', 'Loge', 'Skoll', 'Surtur', 'Anthe', 'Jarnsaxa', 'Greip', 'Tarqeq', 'Aegaeon', 'Saturn', 'Jupiter', 'Ariel', 'Umbriel', 'Titania', 'Oberon', 'Miranda', 'Cordelia', 'Ophelia', 'Bianca', 'Cressida', 'Desdemona', 'Juliet', 'Portia', 'Rosalind', 'Belinda', 'Puck', 'Caliban', 'Sycorax', 'Prospero', 'Setebos', 'Stephano', 'Trinculo', 'Francisco', 'Margaret', 'Ferdinand', 'Perdita', 'Mab', 'Cupid', 'Triton', 'Neptune', 'Nereid', 'Neptune', 'Naiad', 'Thalassa', 'Despina', 'Neptune', 'Galatea', 'Larissa', 'Proteus', 'Halimede', 'Psamathe', 'Sao', 'Laomedeia', 'Neso', 'Charon', 'Nix', 'Hydra', '136108', 'Namaka', 'Dysnomia', 'Makemake'];
		
		public static const ALLIANCE_NAMES:Array/*String*/ = ['Dark Malice', 'Dreadful Under', 'Restless War', 'Royal Banda', 'The Encore', 'SUMMONERS', 'The Six Cheez', 'Exitium Town', 'Giant Legion', 'VOIDWALKERS', 'The Xxelitexx', 'Holy Brigade', 'The Bracelet', 'The Pheonix', 'The Samurai', 'Metal Azeroth', 'Chaotic Clan', 'Gnoman Calls', 'Pavor Knights', 'Sere Lions', 'The Pryde', 'PROPHETICS', 'TYRANNY', 'The Twink', 'The Pally Fury', 'Forsaken Order', 'GANKSTARZ', 'Hit Bliss', 'HORDE', 'The Stockades', 'The Caballeros', 'VENOM', 'Pwnage Flames', 'Wicked Dragons', 'ANAMANIACS', 'REVELATIONISTS', 'Gnomish Blade', 'Angry Foos', 'The Evul', 'The Azeroth', 'The Devil', 'Divine Amicus', 'The Destroyers', 'The Agony', 'Outer Girls', 'NIGHTWOLV', 'FALLEN'];
	}
}